### ISSUE TITLE
Set discount multi script

### ISSUE THREAD

**Issue by dapp-whisperer** [Citadel-DAO/citadel-multisig#1]
The policy ops team will need to set the discount for funding contract(s) regularly. There should be script to modulate these easily.

* Include the ability to loop over multiple funding contracts and set the discount for each one independently.
* The funding contracts should be easy to reference by the symbol of the associated token.
* The current test funding contracts are:

```
  fundingWBTC: "0x2559F79Ffd2b705083A5a23f1fAB4bB03C491435",
  fundingCVX: "0x40927b7bc37380b73DBB60b75d6D5EA308Ec2590",
```

### Output to confirm
* Print the diff in discount rate, it should be clear which asset a given discount is applying to
* The token that is taken in by a particular funding contract can be found with the `asset()` function.

```
  /**
   * @notice Set discount manually, within the constraints of min and max discount values
   * @dev managed by policy operations for rapid response to market conditions
   * @param _discount active discount (in bps)
   */
    function setDiscount(uint256 _discount)
```

**Comment by jorijnsmit** [comment]
solved by #6
